# Fatoração LU

1. Assista o vídeo sobre fatoração LU.
https://youtu.be/MG4Ek9niGTA

A matriz A do vídeo possui fatoração LU, como descrito abaixo.

In [15]:
# observe que neste exemplo, a solução exata é o vetor x = [1, 1, 1, 1]
import numpy as np
import pandas as pd
A = np.array([[2, 3, 1, 5], [6, 13, 5, 19], [2, 19, 10, 23], [4, 10, 11, 31]])
b = np.array([11, 43, 54, 56])
L = np.array([[1, 0, 0, 0], [3, 1, 0, 0], [1, 4, 1, 0], [2, 1, 7, 1]])
U = np.array([[2, 3, 1, 5], [0, 4, 2, 4], [0, 0, 1, 2], [0, 0, 0, 3]])

print('A = \n', A)

print('L = \n', L)

print('U = \n', U)

A_ = L @ U
np.array_equal(A_, A)

print('A_ = \n', A_)

A = 
 [[ 2  3  1  5]
 [ 6 13  5 19]
 [ 2 19 10 23]
 [ 4 10 11 31]]
L = 
 [[1 0 0 0]
 [3 1 0 0]
 [1 4 1 0]
 [2 1 7 1]]
U = 
 [[2 3 1 5]
 [0 4 2 4]
 [0 0 1 2]
 [0 0 0 3]]
A_ = 
 [[ 2  3  1  5]
 [ 6 13  5 19]
 [ 2 19 10 23]
 [ 4 10 11 31]]


Vamos calcular as matrizes $L$ e $U$, e em seguida iremos encontrar a solução do problema. Sabemos de antemão que a solução exata é o vetor $x = [1, 1, 1, 1]$.

In [16]:
import numpy as np
A_ori = np.array([[2, 3, 1, 5], [6, 13, 5, 19], [2, 19, 10, 23], [4, 10, 11, 31]])
b_ori = np.array([11, 43, 54, 56])
L = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
U = np.array([[0, 0,0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]])
print('A = \n', A_ori,'\nL = \n', L,'\nU = \n', U)

A = 
 [[ 2  3  1  5]
 [ 6 13  5 19]
 [ 2 19 10 23]
 [ 4 10 11 31]] 
L = 
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] 
U = 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [17]:
# eliminando os elementos da coluna 1
m10 = - A[1][0]/A[0][0]
A[1] = A[1] +m10*A[0]

m20 = -A[2][0]/A[0][0]
A[2] = A[2] +m20*A[0]

m30 = -A[3][0]/A[0][0]
A[3] = A[3] +m30*A[0]

L[1][0] = -m10
L[2][0] = -m20
L[3][0] = -m30
print('A = \n', A,'\nL = \n', L,'\nU = \n', U)

A = 
 [[ 2  3  1  5]
 [ 0  4  2  4]
 [ 0 16  9 18]
 [ 0  4  9 21]] 
L = 
 [[1 0 0 0]
 [3 1 0 0]
 [1 0 1 0]
 [2 0 0 1]] 
U = 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [18]:
# eliminando os elementos da coluna 2
m21 = -A[2][1]/A[1][1]
A[2] = A[2] +m21*A[1]

m31 = -A[3][1]/A[1][1]
A[3] = A[3] +m31*A[1]

L[2][1] = -m21
L[3][1] = -m31
print('A = \n', A,'\nL = \n', L,'\nU = \n', U)

A = 
 [[ 2  3  1  5]
 [ 0  4  2  4]
 [ 0  0  1  2]
 [ 0  0  7 17]] 
L = 
 [[1 0 0 0]
 [3 1 0 0]
 [1 4 1 0]
 [2 1 0 1]] 
U = 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [19]:
# eliminando os elementos da coluna 3
m32 = -A[3][2]/A[2][2]
A[3] = A[3] +m32*A[2]
L[3][2] = -m32

U = A
print('A = \n', A,'\nL = \n', L,'\nU = \n', U, '\n LU = \n',L @ U, '\nA_ori = \n', A_ori)

A = 
 [[2 3 1 5]
 [0 4 2 4]
 [0 0 1 2]
 [0 0 0 3]] 
L = 
 [[1 0 0 0]
 [3 1 0 0]
 [1 4 1 0]
 [2 1 7 1]] 
U = 
 [[2 3 1 5]
 [0 4 2 4]
 [0 0 1 2]
 [0 0 0 3]] 
 LU = 
 [[ 2  3  1  5]
 [ 6 13  5 19]
 [ 2 19 10 23]
 [ 4 10 11 31]] 
A_ori = 
 [[ 2  3  1  5]
 [ 6 13  5 19]
 [ 2 19 10 23]
 [ 4 10 11 31]]


In [20]:
# encontrando o vetor y, tal que L*y = b
y = np.array([0., 0., 0., 0.])

y[0] = b[0]
y[1] = (b[1] - L[1][0]*y[0])
y[2] = (b[2] - L[2][0]*y[0] - L[2][1]*y[1])
y[3] = (b[3] - L[3][0]*y[0] - L[3][1]*y[1] - L[3][2]*y[2])
print('y = ', y)

y =  [11. 10.  3.  3.]


In [21]:
# encontrando o vetor solucao x, tal que U*x = y
x = np.array([0., 0., 0., 0.])

x[3] = y[3]/U[3][3]
x[2] = (y[2] - U[2][3]*x[3])/U[2][2]
x[1] = (y[1] - U[1][2]*x[2] - U[1][3]*x[3])/U[1][1]
x[0] = (y[0] - U[0][1]*x[1] - U[0][2]*x[2] - U[0][3]*x[3])/U[0][0]
print('x = ', x)

x =  [1. 1. 1. 1.]


2. Atividade: determine a fatoração LU da matriz A abaixo e verifique se sua resposta está correta.

$$A = \begin{bmatrix}
4 & -5 & 6 \\
8 & -6 & 7 \\
12 & -7 & 12
\end{bmatrix}$$

In [ ]:
A = np.array([[4, -5, 6], [8, -6, 7], [12, -7, 12]])
L = np.zeros

# Fatoração Cholesky
3. Assita o vídeo sobre a descomposição de Cholesky
https://youtu.be/bXoGSTBlT5M?t=191


4. Resolva o sistema em https://youtu.be/bXoGSTBlT5M?t=191 utilizando $A^TAx = A^T b$

5. Determine se a matriz $A$ pode ser fatorada na decomposição Cholesky.

$$A=\begin{bmatrix}
4 & -2 & 4 \\
-2 & 5 & -4 \\
4 & -4 & 14
\end{bmatrix}$$

Observe que: 

*   $A = A^t$, portanto $A$ é simétrica

* $A$ é positiva definida pois: 

$det(a_{11}) = 4 > 0$

 $det(\begin{bmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22} \\
\end{bmatrix}$$) = 16 > 0$

 $det(A) = 144 > 0$

**Como $A$ é simétrica e positiva definida, então a decomposição Cholesky pode ser aplicada na matriz $A$.** 



In [ ]:
import numpy as np
A = [[4., -2., 4],[-2, 5, -4],[4, -4, 14]]
np.linalg.det(A)

144.0

6. Determine uma matriz triangular inferior $L$, onde $A = LL^T$ e verifique sua resposta.

$$A=\begin{bmatrix}
4 & -2 & 4 \\
-2 & 5 & -4 \\
4 & -4 & 14
\end{bmatrix}$$

In [ ]:
import numpy as np
n = 3
A = np.array([[4., -2., 4],[-2, 5, -4],[4, -4, 14]])
L = np.zeros((n,n))
for j in range(0,n):
  for i in range(0,n):
    if(i == j):
      L[i][i] = A[i][i]
      for k in range(0,i):
        L[i][i] = L[i][i] - L[i][k]**2
      L[i][i] = (L[i][i])**0.5
    if(i > j):
      L[i][j] = A[i][j]
      for k in range(0,j):
        L[i][j] = L[i][j] - L[i][k]*L[j][k]
      L[i][j] = L[i][j]/L[j][j]
    
print('L = \n', L)
print('L*L = \n', L @ L.T)
print('A = \n', A)

L = 
 [[ 2.  0.  0.]
 [-1.  2.  0.]
 [ 2. -1.  3.]]
L*L = 
 [[ 4. -2.  4.]
 [-2.  5. -4.]
 [ 4. -4. 14.]]
A = 
 [[ 4. -2.  4.]
 [-2.  5. -4.]
 [ 4. -4. 14.]]
