# Matrizes

<a href="https://githubtocolab.com/cn-ufpe/cn-ufpe.github.io/blob/master/material/08_matrizes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab"/></a>

## Inicialização de matrizes

In [1]:
import numpy as np

Inicialização com todos os elementos iguais a zero

In [8]:
A = np.zeros((4,5))
print(A)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -7.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


Todos os elementos iguais a 1

In [5]:
B = np.ones((4, 5))
print(B)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Matriz identidade

In [ ]:
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Matriz diagonal

In [ ]:
np.diag([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
np.diag([1, 1, 1], 1)

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

Matriz aleatória

In [9]:
R = np.random.rand(5,5)
R

array([[0.30784138, 0.66444339, 0.18400325, 0.34270696, 0.33496071],
       [0.70656226, 0.36657395, 0.07181053, 0.41582937, 0.41219621],
       [0.09326208, 0.1279969 , 0.47201115, 0.59501457, 0.71131793],
       [0.24187096, 0.06999248, 0.04713395, 0.41687163, 0.8616848 ],
       [0.94621133, 0.86305918, 0.95925199, 0.63294443, 0.26607556]])

In [10]:
R = 2*(0.5 - np.random.rand(5,5))
R

array([[ 0.04256592, -0.36673502, -0.47672551, -0.70891212,  0.12474136],
       [ 0.24635451,  0.6227327 ,  0.06150757, -0.31397545, -0.97348965],
       [ 0.36348683,  0.34955483, -0.51187937, -0.93139789,  0.1960398 ],
       [-0.26899497,  0.81513794, -0.15688437,  0.54072883, -0.24033394],
       [-0.31687257, -0.88410234, -0.74147569, -0.00950267, -0.30199814]])

A partir de uma lista

In [11]:
A = [[1, 2, 3, 2], [5, 2, 1, 3], [9, 3, 4, 4]]
A = np.array(A)
print(A)

[[1 2 3 2]
 [5 2 1 3]
 [9 3 4 4]]


### Acessar elementos de uma matriz

In [12]:
A[2, 3]

4

Linhas e colunas com o operador "dois pontos"

In [13]:
linha0 = A[[0],:]
print(linha0)
print(linha0.shape)

[[1 2 3 2]]
(1, 4)


In [14]:
A[0:2,:]

array([[1, 2, 3, 2],
       [5, 2, 1, 3]])

In [15]:
A[:]

array([[1, 2, 3, 2],
       [5, 2, 1, 3],
       [9, 3, 4, 4]])

In [16]:
A[:, [2]]

array([[3],
       [1],
       [4]])

In [ ]:
A[:, 0:3]

array([[1, 2, 3],
       [5, 2, 1],
       [9, 3, 4]])

In [ ]:
A[:, [0,3]]

array([[1, 2],
       [5, 3],
       [9, 4]])

### Multiplicação de matrizes

In [18]:
A = np.array([[1, 2, 3], [4, 5, 6], [3, 2, 2]])
b = np.array([[1], [2], [1]])

In [22]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [3, 2, 2]])

In [19]:
b

array([[1],
       [2],
       [1]])

In [20]:
A @ b

array([[ 8],
       [20],
       [ 9]])

In [23]:
A * b

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [ 3,  2,  2]])

In [24]:
print(b.shape)

(3, 1)


In [25]:
b @ b

ValueError: ignored

Transposta

In [26]:
b.T @ b

array([[6]])

In [27]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [3, 2, 2]])

In [28]:
A.T

array([[1, 4, 3],
       [2, 5, 2],
       [3, 6, 2]])

In [29]:
vetor = np.array([1, 2, 3])

In [30]:
vetor

array([1, 2, 3])

In [38]:
vetor.T

array([[1, 2, 3]])

In [37]:
vetor.shape

(3, 1)

In [35]:
vetor.shape = (3, 1)

In [36]:
vetor.T

array([[1, 2, 3]])

In [40]:
vetor

array([[1],
       [2],
       [3]])