#Fundamentos de lógica de programação com python

## Tipo Inteiros

In [160]:
1 + 3 + 7 + 8

19

In [161]:
5 - 2 - 9 - 4

-10

In [162]:
6 * 7*8

336

In [163]:
(43 / 6)/3

2.388888888888889

In [164]:
43 // 8

5

In [165]:
43 % 8

3

In [168]:
2 ** 63 - 1

9223372036854775807

In [169]:
2 ** 1000

10715086071862673209484250490600018105614048117055336074437503883703510511249361224931983788156958581275946729175531468251871452856923140435984577574698574803934567774824230985421074605062371141877954182153046474983581941267398767559165543946077062914571196477686542167660429831652624386837205668069376

##Tipo de ponto flutuante

In [172]:
7.5 + 4, 2.1 ** 2.6, 6.4 - 2

(11.5, 6.8828794995489115, 4.4)

##Variáveis

In [180]:
pi = 3.1415
raio = 2
pi * (raio ** 2)

12.566

In [196]:
raio = 1
pi * (raio ** 2)

3

In [176]:
nao_existe

NameError: ignored

In [199]:
type(raio)

int

In [200]:
type(int(pi))

int

##Cadeia de Caracteres (String)

In [201]:
print("Olá Mundo")

Olá Mundo


In [202]:
type("Lucas"), type('Lucas'), type("""Lucas"""), type('''Lucas''')

(str, str, str, str)

In [203]:
nome = 'Lucas'
nome

'Lucas'

In [ ]:
nome = '''Lucas' name'''
nome

"Lucas' name"

In [205]:
nome = "Lucas' name"
nome

"Lucas' name"

In [207]:
nome = """Lucas' "name" """
nome

'Lucas\' "name" '

In [217]:
nome = 'Lucas \n Rodolfo '
print(nome)

Lucas 
 Rodolfo 


In [212]:
nome = '''Lucas
 Rodolfo'''
print(nome)

Lucas
 Rodolfo


##Tipo Booleanos

In [ ]:
True, False, type(True), type(False)

(True, False, bool, bool)

In [ ]:
True and True, True and False, False and True, False and False

(True, False, False, False)

In [ ]:
True or True, True or False, False or True, False or False

(True, True, True, False)

In [214]:
5 < 6, 5 == 6, 5 == 4, 5 == 5, 5 != 4, 5 != 5, 'Lucas' == "Lucas"

(True, False, False, True, True, False, True)

In [215]:
lucas = "Lucas"
lucas == "lucas"

False

In [220]:
idade = int(input())
idade

40


40

In [336]:
#idade = int(input("digite seu sua idade: "))
idade = int(input())
idade

digite seu sua diade: 40


40

##Desvios Lógicos

In [234]:
idade = 19

if (idade >= 18):
  print("Maior de idade: ", idade)

Maior de idade:  19


In [240]:
idade = 16
if (idade >= 18):
  print("Maior de idade: ", idade)
else:
  print("Menor de idade: ", idade)

Menor de idade:  16


In [241]:
idade = int(input())

if (idade >= 18) and (idade < 64):
  print("Maior de idade: ", idade)   
elif idade >= 65:
  print("pessoa idosa: ", idade)
else:
  print("Menor de idade: ", idade)

32
Maior de idade:  32


##Funções

In [242]:
def classificarIdade(idade, nome):
  if (idade >= 18) and idade < 64:
    return f'{nome} é maior de idade: {idade}'
  elif idade >= 65:
    return f'{nome} é pessoa idosa: {idade}'
  else:
    return f'{nome} é menor de idade: {idade}'

#classificarIdade(70, "Boo")
classificarIdade(70, input())

joao


'joao é pessoa idosa: 70'

In [243]:
classificarIdade(25, "Lucas")

'Lucas é maior de idade: 25'

##Sequencias (Listas)

In [244]:
Lista = []
type(Lista)

list

In [246]:
lista = [10, -2, 3, 4, 5, 6]
lista

[10, -2, 3, 4, 5, 6]

In [250]:
#lista = [1, 4.5, True, []]
lista = [1, 4.5, True, [1, 4.5, True]]
lista

[1, 4.5, True, [1, 4.5, True]]

##Acesso a elementos

In [256]:
lista[1],lista[2],lista[3],lista[3][1]
#lista[1] = 8.9
#lista[1]

(4.5, True, [1, 4.5, True], 4.5)

In [257]:
lista[4]

IndexError: ignored

In [261]:
len(lista)

4

In [264]:
lista[len(lista) - 1], lista[len(lista) - 2] 

([1, 4.5, True], True)

In [265]:
lista[-1], lista[ -2], lista[0], lista[1]

([1, 4.5, True], True, 1, 4.5)

##Fatiamento

In [266]:
lista

[1, 4.5, True, [1, 4.5, True]]

In [267]:
lista[0:3]

[1, 4.5, True]

In [268]:
lista[0:len(lista)]

[1, 4.5, True, [1, 4.5, True]]

In [269]:
lista[1:3], lista[2:len(lista)]

([4.5, True], [True, [1, 4.5, True]])

In [270]:
lista[:]

[1, 4.5, True, [1, 4.5, True]]

In [272]:
numeros = list(range(1,11))
numeros

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
numeros[1:7]

[2, 3, 4, 5, 6, 7]

In [274]:
numeros[1:10:2]

[2, 4, 6, 8, 10]

In [275]:
numeros[0:11:2]

[1, 3, 5, 7, 9]

In [276]:
list(range(1,32,2))

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31]

In [277]:
nome = 'Lucas Rodolfo'
nome[0], nome[:6]

('L', 'Lucas ')

##Adição e Remoção

In [278]:
dir(numeros)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [292]:
help(numeros.pop)

Help on built-in function pop:

pop(index=-1, /) method of builtins.list instance
    Remove and return item at index (default last).
    
    Raises IndexError if list is empty or index is out of range.



In [293]:
numeros.pop()

12

In [294]:
numeros

[-1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 5.5, 11]

In [295]:
numeros.append(5.5)
numeros.append(5.5)
numeros

[-1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 5.5, 11, 5.5, 5.5]

In [299]:
numeros.insert(0,-15)
numeros

[-15, -5, -15, -1, -1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 5.5, 11, 5.5, 5.5]

In [301]:
numeros.pop()

5.5

In [302]:
numeros

[-15, -5, -15, -1, -1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 5.5, 11]

In [303]:
numeros.extend([11, 12])

In [304]:
numeros

[-15, -5, -15, -1, -1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 5.5, 11, 11, 12]

In [305]:
[1,3] + [2,4]

[1, 3, 2, 4]

In [307]:
[1,3] * 5

[1, 3, 1, 3, 1, 3, 1, 3, 1, 3]

In [308]:
"Lucas " + "Rodolfo"

'Lucas Rodolfo'

In [309]:
"Bla "  *4

'Bla Bla Bla Bla '

##Laços

In [310]:
idades=[17, 25, 70]
classificarIdade(idades[1],"Lucas")

'Lucas é maior de idade: 25'

In [311]:
classificarIdade(idades[0],"Lucas"),classificarIdade(idades[1],"Lucas"),classificarIdade(idades[2],"Lucas")

('Lucas é menor de idade: 17',
 'Lucas é maior de idade: 25',
 'Lucas é pessoa idosa: 70')

In [314]:
for j in idades:
  print(classificarIdade(j, "Pessoa"))

Pessoa é menor de idade: 17
Pessoa é maior de idade: 25
Pessoa é pessoa idosa: 70


In [319]:
idades.append(156)
idades

[17, 25, 70, 101, 101, 101, 156]

In [323]:
for i in range(0,len(idades),2):
  print(classificarIdade(idades[i],"Pessoa"))

Pessoa é menor de idade: 17
Pessoa é pessoa idosa: 70
Pessoa é pessoa idosa: 101
Pessoa é pessoa idosa: 156


In [325]:
i = 0
while (i < len(idades)):
  print(classificarIdade(idades[i],"Pessoa"))
  i+=1

Pessoa é menor de idade: 17
Pessoa é maior de idade: 25
Pessoa é pessoa idosa: 70
Pessoa é pessoa idosa: 101
Pessoa é pessoa idosa: 101
Pessoa é pessoa idosa: 101
Pessoa é pessoa idosa: 156


##Matrizes

In [330]:
m = [[1,2,3],[4,5,6],[7,8,9]]
m

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [331]:
def lerMatriz(matriz):
  linhas, colunas = (len(matriz), len(matriz[0]))
  print(linhas, colunas)

lerMatriz(m)

3 3


In [332]:
def lerMatriz(matriz):
  linhas, colunas = (len(matriz), len(matriz[0]))
  print(linhas, colunas)
  for j in range(colunas):
    for i in range(linhas):
      print(matriz[i][j])

lerMatriz(m)

3 3
1
4
7
2
5
8
3
6
9


In [333]:
def lerMatriz(matriz):
  linhas, colunas = (len(matriz), len(matriz[0]))
  print(linhas, colunas)
  for i in range(linhas):
    for j in range(colunas):
      matriz[i][j] = matriz[i][j]*2
      print(matriz[i][j])

lerMatriz(m)

3 3
2
4
6
8
10
12
14
16
18


##Operações com listas

In [ ]:
numeros = list(range(1,5))
numeros

[1, 2, 3, 4]

In [ ]:
soma = 0
for i in range(0,len(numeros)):
  soma = soma + numeros[i]
print(soma)

10


In [ ]:
teste_de_soma = sum(numeros)
print(sum(numeros))

10


In [ ]:
import math
print(math.fsum(numeros))

10.0


In [ ]:
import numpy as np
m = np.ones([50,50])
print(m)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


##Dicionário

In [ ]:
linguas = {'pt': 'português', 'en': 'inglês'} # Chave: Valor o conjunto é chamado de item
linguas['pt'], linguas['en']

('português', 'inglês')

In [ ]:
linguas['es']

KeyError: ignored

In [ ]:
linguas['es'] = 'Espanhol'
linguas

{'en': 'inglês', 'es': 'Espanhol', 'pt': 'português'}

In [ ]:
for chaves in linguas:
  print(chaves)

pt
en
es


In [ ]:
for chaves in linguas.keys():
  print(chaves)

pt
en
es


In [ ]:
for valores in linguas.values():
  print(valores)

português
inglês
Espanhol


In [ ]:
for chave, valor in linguas.items():
  print(chaves, valor)

es português
es inglês
es Espanhol
